Added IncludeContextAttributes from Serilog Logger
pada57/serilog-sinks-influxdb pull request #17
Opened 2022-07-15 10:06 UTC by tyagira

Hello 
The existing library is not supporting the context attributes as generated by the serilog logger.
Only the predefined tags and fields are generated in InfuxDB bucket.
I have extended the library, that now on demand , it will create the context attributes as tags in InfluxDB bucket.
Please review

2022-07-18 18:50 UTC, pada57 commented
Thanks for your PR, I will look on phone as in vacation. Will not merge before August

2022-08-13 13:29 UTC, pada57 requested changes
Could we merge this PR with #16  ?

2022-08-13 13:29 UTC, pada57 commented on Serilog.Sinks.InfluxDB/Sinks/InfluxDB/InfluxDBSink.cs
> +                if(_includeContextAttributes)
is the intent rather similar to open PR https://github.com/pada57/serilog-sinks-influxdb/pull/16

i would proprose we have two collections ExtendedTags and Fields.

in your case ContextAttributes are always added as Tags, cannot be a Field.
also "ContextAttributes" naming is rather confusing

would the other PR with some improvements of course would be workable solution in your use case ?

2022-08-13 13:29 UTC, pada57 commented on Serilog.Sinks.InfluxDB/Sinks/InfluxDB/InfluxDBSinkOptions.cs
> +        public bool? IncludeContextAttributes { get; set; } = false;
naming confusing ?

2023-01-27 07:12 UTC, tom-englert commented
If someone is still interested in this, it should be implemented like in #16

2023-01-27 07:12 UTC, closed without merging