Change ProcId from int to string to match V2 change and the RFC.
pada57/serilog-sinks-influxdb pull request #31
Opened 2023-01-26 20:29 UTC by MarkZither

This is to resolve #29 and #30 

Small change to apply the ProcId fix from V2 to V1.
This is a bit dangerous, for anyone currently using it this will be a breaking change.

I have created a new package so we can test the fix quickly,  https://www.nuget.org/packages/Serilog.Sinks.InfluxDBV1.Syslog/2.0.0-alpha.1

2023-01-27 07:09 UTC, tom-englert requested changes

2023-01-27 07:09 UTC, tom-englert commented on Serilog.Sinks.InfluxDB/Serilog.Sinks.InfluxDB.csproj
> +    <Version>2.0.0-alpha.1</Version>
Isn't that very confusing? shouldn't we stay with 1.x for Influx 1.x, instead of introducing a new package with different name?

2023-01-28 06:51 UTC, pada57 commented
solved by https://www.nuget.org/packages/Serilog.Sinks.InfluxDB.V1.Syslog/2.0.0

2023-01-28 06:51 UTC, closed without merging

2023-01-30 08:28 UTC, tom-englert commented
@pada57 Now that you turned the versioning upside down, the readme is all wrong - will you fix this?

2023-01-30 08:33 UTC, tom-englert commented
Also the tags are totally confusing now, there is a 2.0nuget and a 2.0.0nuget, and 2.0.0 is not the predecessor of 2.0.1 - who will ever be able to follow this?

2023-01-30 13:57 UTC, pada57 commented
done readme updated, v2.3.3 reflecting in readme of nuget as well @tom-englert